apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - bases/cfgate.io_cloudflaretunnels.yaml
  - bases/cfgate.io_cloudflarednses.yaml
  - bases/cfgate.io_cloudflareaccesspolicies.yaml
