"$schema" = "./node_modules/wrangler/config-schema.json"
name = "cfgate-worker"
main = "./src/index.ts"
compatibility_date = "2026-01-31"
compatibility_flags = ["nodejs_compat"]
workers_dev = false

[assets]
directory = "./dist"
binding = "ASSETS"
run_worker_first = true

[[routes]]
pattern = "cfgate.io"
custom_domain = true

[observability]
enabled = true
head_sampling_rate = 0.05
